import { StyleSheet } from 'react-native';
import { withOpacity } from '@controleonline/../../src/styles/branding';

const createStyles = (ppcColors, brandColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: ppcColors.appBg,
    },
    hero: {
      marginHorizontal: 14,
      marginTop: 12,
      marginBottom: 14,
      borderRadius: 24,
      overflow: 'hidden',
      backgroundColor: ppcColors.panelBg,
      borderWidth: 1,
      borderColor: ppcColors.border,
      shadowColor: brandColors.primary,
      shadowOpacity: 0.12,
      shadowOffset: { width: 0, height: 12 },
      shadowRadius: 22,
      elevation: 5,
      position: 'relative',
    },
    heroGlow: {
      position: 'absolute',
      top: -74,
      left: 52,
      width: 180,
      height: 180,
      borderRadius: 999,
      backgroundColor: withOpacity(ppcColors.accent, 0.16),
    },
    heroTopRow: {
      paddingHorizontal: 18,
      paddingVertical: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 14,
    },
    heroTopRowCompact: {
      flexDirection: 'column',
      alignItems: 'stretch',
    },
    heroIdentity: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    heroContent: {
      flex: 1,
    },
    heroLogoWrap: {
      width: 52,
      height: 52,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: withOpacity(ppcColors.accent, 0.28),
      backgroundColor: withOpacity(ppcColors.accent, 0.06),
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroLogo: {
      width: 30,
      height: 30,
    },
    heroTitle: {
      color: ppcColors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
    },
    heroSubtitle: {
      marginTop: 3,
      color: ppcColors.textSecondary,
      fontSize: 13,
      fontWeight: '600',
    },
    heroActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flexWrap: 'wrap',
      justifyContent: 'flex-end',
    },
    heroActionsCompact: {
      width: '100%',
      justifyContent: 'space-between',
    },
    countPill: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: withOpacity(ppcColors.accent, 0.22),
      backgroundColor: withOpacity(ppcColors.accent, 0.1),
      alignItems: 'center',
      minWidth: 108,
    },
    countNumber: {
      color: ppcColors.accent,
      fontSize: 13,
      fontWeight: '900',
      lineHeight: 16,
      textTransform: 'uppercase',
    },
    list: {
      paddingHorizontal: 14,
      paddingBottom: 28,
      paddingTop: 2,
      gap: 12,
    },
    columnWrapper: {
      gap: 12,
    },
    itemWrapper: {
      flex: 1,
    },
    addButton: {
      width: 52,
      height: 52,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: withOpacity(ppcColors.accent, 0.32),
      backgroundColor: ppcColors.accent,
      shadowColor: ppcColors.accent,
      shadowOpacity: 0.28,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 16,
      elevation: 5,
    },
    skeletonWrap: {
      flex: 1,
      paddingHorizontal: 14,
      paddingTop: 2,
      paddingBottom: 24,
      gap: 12,
    },
    skeletonCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: ppcColors.borderSoft,
      backgroundColor: ppcColors.cardBg,
      paddingHorizontal: 14,
      paddingVertical: 14,
    },
    skeletonHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    skeletonCircle: {
      width: 40,
      height: 40,
      borderRadius: 999,
      backgroundColor: ppcColors.cardBgSoft,
      borderWidth: 1,
      borderColor: ppcColors.border,
      marginRight: 10,
    },
    skeletonTitleWrap: {
      flex: 1,
      gap: 8,
    },
    skeletonLine: {
      borderRadius: 999,
      backgroundColor: ppcColors.cardBgSoft,
      borderWidth: 1,
      borderColor: ppcColors.border,
      height: 12,
    },
    skeletonLineLong: {
      width: '68%',
    },
    skeletonLineShort: {
      width: '44%',
      height: 10,
    },
    skeletonPillsRow: {
      marginTop: 14,
      flexDirection: 'row',
      gap: 8,
    },
    skeletonPill: {
      height: 28,
      borderRadius: 999,
      backgroundColor: ppcColors.cardBgSoft,
      borderWidth: 1,
      borderColor: ppcColors.border,
      width: 78,
    },
    skeletonPillWide: {
      width: 112,
    },
    skeletonFooterRow: {
      marginTop: 14,
      paddingTop: 10,
      borderTopWidth: 1,
      borderTopColor: ppcColors.border,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    skeletonTag: {
      width: 86,
      height: 22,
      borderRadius: 999,
      backgroundColor: ppcColors.cardBgSoft,
      borderWidth: 1,
      borderColor: ppcColors.border,
    },
    skeletonAction: {
      width: 138,
      height: 28,
      borderRadius: 999,
      backgroundColor: ppcColors.cardBgSoft,
      borderWidth: 1,
      borderColor: ppcColors.border,
    },
  });

export default createStyles;
