import { StyleSheet } from 'react-native'
import { withOpacity } from '@controleonline/../../src/styles/branding'

const createStyles = ppcColors => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: ppcColors.appBg,
  },
  body: {
    flex: 1,
  },
  content: {
    padding: 8,
    paddingBottom: 120,
    gap: 8,
  },
  headerCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: ppcColors.borderSoft,
    backgroundColor: ppcColors.cardBg,
    padding: 10,
  },
  productsCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: ppcColors.borderSoft,
    backgroundColor: ppcColors.cardBg,
    padding: 4,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  loadingText: {
    color: ppcColors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  emptyText: {
    color: ppcColors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    paddingVertical: 20,
  },
  itemRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: ppcColors.border,
    backgroundColor: ppcColors.cardBg,
    paddingHorizontal: 8,
    paddingVertical: 7,
    marginBottom: 4,
  },
  rootFamilySeparator: {
    borderTopColor: withOpacity(ppcColors.textPrimary, 0.28),
  },
  itemMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemContent: {
    flex: 1,
    minWidth: 0,
  },
  text: {
    color: ppcColors.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  qtyText: {
    color: ppcColors.accentInfo,
    fontWeight: '900',
  },
  statusMarker: {
    fontSize: 18,
    lineHeight: 18,
    fontWeight: '900',
  },
  metaWrap: {
    marginTop: 5,
    gap: 4,
  },
  subText: {
    color: ppcColors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '600',
  },
  groupWrap: {
    marginTop: 6,
  },
  groupTitlePill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: withOpacity(ppcColors.accentInfo, 0.28),
    backgroundColor: withOpacity(ppcColors.accentInfo, 0.1),
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginBottom: 4,
  },
  groupTitle: {
    color: ppcColors.accentInfo,
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '900',
  },
  groupItem: {
    paddingVertical: 3,
  },
  groupItemMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  groupItemContent: {
    flex: 1,
    minWidth: 0,
  },
  groupItemText: {
    color: ppcColors.textPrimary,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  groupItemMetaWrap: {
    marginTop: 2,
    gap: 2,
  },
  groupItemMetaText: {
    color: ppcColors.textSecondary,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '600',
  },
  itemActions: {
    alignItems: 'flex-end',
  },
  groupItemActions: {
    display: 'none',
  },
  progressPill: {
    minWidth: 48,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: withOpacity(ppcColors.accentInfo, 0.36),
    backgroundColor: withOpacity(ppcColors.accentInfo, 0.1),
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignItems: 'center',
  },
  progressPillComplete: {
    borderColor: withOpacity('#16A34A', 0.42),
    backgroundColor: withOpacity('#16A34A', 0.12),
  },
  progressPillText: {
    color: ppcColors.accentInfo,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
  },
  progressPillTextComplete: {
    color: '#16A34A',
  },
  queueBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    gap: 5,
  },
  queueBadgeDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
  },
  queueBadgeDotHidden: {
    display: 'none',
  },
  queueBadgeText: {
    fontSize: 9,
    lineHeight: 12,
    fontWeight: '900',
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: ppcColors.border,
    backgroundColor: ppcColors.cardBg,
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    gap: 8,
  },
  footerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  footerLabel: {
    color: ppcColors.textSecondary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  footerCounter: {
    color: ppcColors.textPrimary,
    fontSize: 24,
    lineHeight: 28,
    fontWeight: '900',
  },
  scanInput: {
    minHeight: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: ppcColors.border,
    backgroundColor: ppcColors.panelBg,
    color: ppcColors.textPrimary,
    paddingHorizontal: 10,
    fontSize: 14,
    fontWeight: '700',
  },
  readyButton: {
    minHeight: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: withOpacity('#16A34A', 0.42),
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  readyButtonDisabled: {
    opacity: 0.42,
  },
  readyButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
})

export default createStyles
