export {
  ReportCardShell,
  MetricTile,
  formatInteger,
  formatDecimal,
  formatPercent,
  formatSignedInteger,
  formatSignedPercent,
  normalizeNumber,
  normalizeText,
  resolveAccentColor,
  resolveProgressColor,
  OperationalInsightsStatusCard,
  OperationalInsightsKpiCard,
  OperationalInsightsRankingCard,
  OperationalInsightsTrendCard,
  OperationalInsightsAbcCard,
} from '@controleonline/ui-report/src/react/components/operationalInsights';
